/* eslint-disable @typescript-eslint/no-explicit-any */
// Phase 6 local vertical pages: 7 verticals x 6 neighborhoods from
// content/local-pages.json, composed into the same block layouts CMS pages
// use. Copy is generated by interpolating real vertical + neighborhood
// details, not by swapping two words; the data file carries the substance.

import data from '../../content/local-pages.json'
import {
  rtDoc,
  websitesPricingBlock,
  phoneDemoBlock,
  guaranteesBlock,
  PHONE_DISPLAY,
} from '@/seed/reset-content'

export type Vertical = (typeof data.verticals)[number]
export type Neighborhood = (typeof data.neighborhoods)[number]

export const VERTICALS: Vertical[] = data.verticals
export const NEIGHBORHOODS: Neighborhood[] = data.neighborhoods

const fill = (s: string, n: Neighborhood, v: Vertical) =>
  s.replaceAll('{n}', n.name).replaceAll('{v}', v.label)

export const localPageSlug = (v: Vertical, n: Neighborhood) =>
  `${v.slug}-website-design-${n.slug}`

export type LocalPage = { vertical: Vertical; neighborhood: Neighborhood; slug: string }

export const ALL_LOCAL_PAGES: LocalPage[] = VERTICALS.flatMap((vertical) =>
  NEIGHBORHOODS.map((neighborhood) => ({
    vertical,
    neighborhood,
    slug: localPageSlug(vertical, neighborhood),
  })),
)

export function findLocalPage(slug: string): LocalPage | null {
  return ALL_LOCAL_PAGES.find((p) => p.slug === slug) ?? null
}

export const localPageTitle = (p: LocalPage) =>
  `${p.vertical.label} Website Design in ${p.neighborhood.title}, Houston | Black Hart Consulting`

export const localPageMeta = (p: LocalPage) =>
  `Websites for ${p.vertical.plural.toLowerCase()} in ${p.neighborhood.name}: $699 five-page sites live in 7 days, a phone desk that answers every call, and a free demo before you pay.`

// Compose the block layout rendered by RenderBlocks (same components as CMS pages).
export function localPageLayout(p: LocalPage): any[] {
  const { vertical: v, neighborhood: n } = p
  const t = (s: string) => fill(s, n, v)

  return [
    {
      blockType: 'hero',
      eyebrow: `${n.title}, Houston · ${v.label} websites`,
      headline: t(`Websites that book ${v.servicesWord} jobs in {n}.`),
      subheadline: t(
        `Built in 7 days at a fixed price, with the search structure that puts a ${v.label.toLowerCase()} business in front of {n} customers, and a front desk that answers when you cannot.`,
      ),
      align: 'left',
      backgroundImageUrl: (v as { heroImage?: string }).heroImage,
      overlayStrength: 'heavy',
      ctas: [
        { label: 'See your site first', href: '/free-demo-site', variant: 'primary' },
        { label: `Call the front desk ${PHONE_DISPLAY}`, href: 'tel:+18664349777', variant: 'ghost' },
      ],
    },
    {
      blockType: 'richText',
      eyebrow: t(`${v.plural} in {n}`),
      maxWidth: 'prose',
      content: rtDoc([
        ['p', t(v.intro)],
        ['h3', t(`Why {n} is its own market`)],
        ['p', n.blurb],
      ]),
    },
    {
      blockType: 'outcomeCards',
      eyebrow: 'The three leaks',
      headline: t(`Where ${v.servicesWord} businesses in {n} lose work.`),
      cards: v.painPoints.map((pp: any) => ({ title: pp.title, blurb: t(pp.body) })),
    },
    {
      blockType: 'richText',
      eyebrow: 'What your site needs',
      maxWidth: 'prose',
      variant: 'card',
      content: rtDoc([
        ['h2', t(`What a ${v.label.toLowerCase()} website needs`)],
        ...v.siteNeeds.map((sn: any): ['p', string] => ['p', `${sn.label}. ${t(sn.why)}`]),
      ]),
    },
    websitesPricingBlock(),
    phoneDemoBlock,
    guaranteesBlock,
    {
      blockType: 'faq',
      eyebrow: 'Common questions',
      headline: t(`${v.label} websites in {n}, answered.`),
      mode: 'manual',
      items: v.faqs.map((f: any) => ({ question: t(f.q), answer: t(f.a) })),
    },
    {
      blockType: 'cta',
      headline: 'See your new site before you pay a dollar.',
      description: t(
        'Send your business name and Google listing. A working mockup of your {v} site, built from your real services and reviews, is in your inbox within 48 hours. No call, no obligation.',
      ).replaceAll('{v}', v.servicesWord),
      variant: 'emphasized',
      primaryCta: { label: 'See your site first', href: '/free-demo-site' },
      secondaryCta: { label: `Call the front desk ${PHONE_DISPLAY}`, href: 'tel:+18664349777' },
    },
  ]
}

export function localPageSchema(p: LocalPage, siteUrl: string): Record<string, unknown> {
  const { vertical: v, neighborhood: n } = p
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name: `${v.label} website design in ${n.title}, Houston`,
    serviceType: 'Website design',
    provider: {
      '@type': 'LocalBusiness',
      '@id': `${siteUrl}/#business`,
      name: 'Black Hart Consulting',
      telephone: PHONE_DISPLAY,
      url: siteUrl,
    },
    areaServed: {
      '@type': 'Place',
      name: `${n.title}, Houston, TX`,
    },
    audience: { '@type': 'Audience', audienceType: v.plural },
    url: `${siteUrl}/houston/${p.slug}`,
  }
}
