\echo === REAL-DOMAIN REACHABLE BASE: by vertical
with s as (select vertical, neighborhood, (site_score->>'https')='true' https, (site_score->>'viewportOk')='true' vp, (site_score->>'lighthouseMobile')::int lh, (site_score->>'designQuality')::int dq, nullif(site_score->>'copyrightYear','')::int cy, coalesce(site_score->>'builderFingerprint','custom') b
 from leads where website_url is not null and (site_score->>'reachable')='true' and website_url !~* 'instagram\.com|facebook\.com|fb\.com|tiktok\.com|linktr\.ee|yelp\.com|google\.com/|business\.site|hub\.biz|booksy|vagaro|square\.site|squareup\.com|nextdoor')
select vertical, count(*) n, count(lh) scored, round(avg(lh),1) avg_lh, percentile_cont(0.5) within group (order by lh) med, round(100.0*count(*) filter (where lh<50)/count(lh),1) pct_under50, round(100.0*count(*) filter (where lh>=90)/count(lh),1) pct_90, round(100.0*count(*) filter (where not https)/count(*),1) pct_nohttps, round(100.0*count(*) filter (where not vp)/count(*),1) pct_novp, round(100.0*count(*) filter (where cy<=2022)/nullif(count(cy),0),1) pct_stale_of_dated, round(100.0*count(*) filter (where dq<=30)/nullif(count(dq),0),1) pct_dated_design
from s group by 1 order by 2 desc;
\echo === by builder
with s as (select (site_score->>'lighthouseMobile')::int lh, coalesce(site_score->>'builderFingerprint','custom') b
 from leads where website_url is not null and (site_score->>'reachable')='true' and website_url !~* 'instagram\.com|facebook\.com|fb\.com|tiktok\.com|linktr\.ee|yelp\.com|google\.com/|business\.site|hub\.biz|booksy|vagaro|square\.site|squareup\.com|nextdoor')
select b, count(*) n, count(lh) scored, round(avg(lh),1) avg_lh, round(100.0*count(*) filter (where lh<50)/nullif(count(lh),0),1) pct_under50 from s group by 1 order by 2 desc;
\echo === deciles
select (((site_score->>'lighthouseMobile')::int)/10)*10 d, count(*) from leads where website_url is not null and site_score->>'lighthouseMobile' is not null and website_url !~* 'instagram\.com|facebook\.com|fb\.com|tiktok\.com|linktr\.ee|yelp\.com|google\.com/|business\.site|hub\.biz|booksy|vagaro|square\.site|squareup\.com|nextdoor' group by 1 order by 1;
\echo === by neighborhood n>=30 scored
select coalesce(neighborhood,'(none)') nb, count(*) scored, round(avg((site_score->>'lighthouseMobile')::int),1) avg_lh, round(100.0*count(*) filter (where (site_score->>'lighthouseMobile')::int<50)/count(*),1) pct_under50 from leads where website_url is not null and site_score->>'lighthouseMobile' is not null and website_url !~* 'instagram\.com|facebook\.com|fb\.com|tiktok\.com|linktr\.ee|yelp\.com|google\.com/|business\.site|hub\.biz|booksy|vagaro|square\.site|squareup\.com|nextdoor' group by 1 having count(*)>=30 order by 4 desc;
\echo === hygiene totals on base
with s as (select (site_score->>'https')='true' https, (site_score->>'viewportOk')='true' vp, (site_score->>'designQuality')::int dq, nullif(site_score->>'copyrightYear','')::int cy, coalesce(site_score->>'builderFingerprint','custom') b
 from leads where website_url is not null and (site_score->>'reachable')='true' and website_url !~* 'instagram\.com|facebook\.com|fb\.com|tiktok\.com|linktr\.ee|yelp\.com|google\.com/|business\.site|hub\.biz|booksy|vagaro|square\.site|squareup\.com|nextdoor')
select count(*) n, count(*) filter (where not https) nohttps, count(*) filter (where not vp) novp, count(cy) cy_n, count(*) filter (where cy<=2022) stale, count(dq) dq_n, count(*) filter (where dq<=30) dated, count(*) filter (where b<>'custom') on_builder, count(*) filter (where b='wix') wix, count(*) filter (where b='godaddy') godaddy, count(*) filter (where b='squarespace') sqsp, count(*) filter (where b='weebly') weebly from s;
