import type { Metadata } from 'next'
import Link from 'next/link'
import { Container } from '@/components/Container'
import { getCachedSiteSettings } from '@/lib/payload-cache'
import { phoneHref, mailtoHref } from '@/lib/contact'

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'How Black Hart Consulting collects, uses, and protects your information.',
  robots: { index: true, follow: true },
}

// If this policy materially changes, update LAST_UPDATED and re-deploy —
// the date is shown at the top so visitors can see when it last changed.
const LAST_UPDATED = 'April 20, 2026'

export default async function PrivacyPolicyPage() {
  const siteSettings = await getCachedSiteSettings()
  const email = siteSettings?.contactEmail ?? 'hello@blackhartconsulting.com'
  const phone = siteSettings?.contactPhone ?? '(866) 434-9777'
  const phoneHrefVal = phoneHref(phone)
  const emailHrefVal = mailtoHref(email)

  return (
    <div className="pb-20">
      <Container size="md" className="py-20 sm:py-28">
        <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[var(--color-fg-muted)] mb-5">
          Legal
        </p>
        <h1 className="font-serif font-semibold text-[clamp(2.25rem,5vw,4rem)] leading-[1.04] tracking-[-0.03em]">
          Privacy Policy
        </h1>
        <p className="mt-6 font-mono text-[12px] tracking-[0.1em] text-[var(--color-fg-muted)]">
          Last updated: {LAST_UPDATED}
        </p>
        <p className="mt-6 text-[17px] leading-[1.55] text-[var(--color-fg-muted)] max-w-prose">
          Black Hart Consulting LLC (&ldquo;Black Hart,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) respects your
          privacy. This page explains what information we collect, how we use
          it, and the choices you have. Plain language, no dark patterns.
        </p>

        <div className="prose mt-12 text-[16px] leading-[1.7]">
          <Section title="Who we are">
            <p>
              Black Hart Consulting LLC is a Texas-registered consulting firm
              providing website design, SEO, app development, and hosting
              services. You can reach us at{' '}
              {emailHrefVal ? (
                <a href={emailHrefVal} className={linkCls}>{email}</a>
              ) : email}
              {' '}or{' '}
              {phoneHrefVal ? (
                <a href={phoneHrefVal} className={cn(linkCls, 'font-mono tracking-[0.02em]')}>{phone}</a>
              ) : phone}.
            </p>
          </Section>

          <Section title="What we collect">
            <ul>
              <li>
                <strong>Contact form submissions</strong> &mdash; your name, email,
                optional phone, optional company, optional project details, and
                the message you send us.
              </li>
              <li>
                <strong>SMS opt-in records</strong> &mdash; if you opt in to text
                messages, we log your name, phone number, the opt-in source
                (website form or contact form), the disclaimer text you
                agreed to, your IP address, your browser user-agent, and the
                timestamp. This record is our legal proof that you consented.
              </li>
              <li>
                <strong>Server logs</strong> &mdash; standard web server logs
                (IP address, request path, timestamp, user-agent) generated by
                our hosting infrastructure. Used for operations and abuse
                prevention, not profiling.
              </li>
              <li>
                <strong>Cookies</strong> &mdash; the marketing site is largely
                cookie-free. The admin interface uses a single
                authentication cookie and is accessible only to us.
              </li>
            </ul>
          </Section>

          <Section title="How we use it">
            <ul>
              <li>To reply to your inquiries and do the work you&rsquo;ve engaged us for.</li>
              <li>
                To send you customer-care text messages that you opted in to
                receive &mdash; one-to-one replies to your contact-form
                inquiry and confirmations of consulting calls you request, up
                to 10 per month. We do not send marketing, promotional, or
                bulk messages.
              </li>
              <li>To keep the site secure and operating correctly.</li>
              <li>To comply with legal obligations (tax, A2P 10DLC carrier records).</li>
            </ul>
            <p>
              We do not sell your information. We do not share it with
              third-party advertisers. We do not use your information to
              train machine-learning models.
            </p>
          </Section>

          <Section title="Who we share it with">
            <p>We use a small set of trusted sub-processors to run the service:</p>
            <ul>
              <li><strong>Resend</strong> &mdash; transactional email delivery (contact-form notifications).</li>
              <li><strong>Quo (OpenPhone)</strong> &mdash; SMS delivery for opted-in contacts.</li>
              <li><strong>DigitalOcean</strong> &mdash; hosting (the droplet and the managed Spaces bucket that stores uploaded media).</li>
            </ul>
            <p>
              Each sub-processor sees only the data needed for its job. We do
              not authorize any of them to use your data for their own
              purposes.
            </p>
          </Section>

          <Section title="How long we keep it">
            <ul>
              <li><strong>Contact-form submissions</strong>: kept while the business relationship is active and for up to 3 years afterward.</li>
              <li><strong>SMS opt-in records</strong>: kept for as long as you are opted in, plus 4 years after opt-out (required for A2P 10DLC audit).</li>
              <li><strong>Server logs</strong>: rotated after 30 days.</li>
            </ul>
          </Section>

          <Section title="Your rights">
            <p>You can, at any time:</p>
            <ul>
              <li>Ask us what data we have about you.</li>
              <li>Ask us to correct or delete it.</li>
              <li>
                Opt out of SMS by replying <span className="font-mono">STOP</span> to any
                text, or by emailing us at{' '}
                {emailHrefVal ? <a href={emailHrefVal} className={linkCls}>{email}</a> : email}.
              </li>
              <li>Opt out of email by replying to any message and saying so.</li>
            </ul>
            <p>
              California residents: you have the rights described in the
              California Consumer Privacy Act (CCPA). We will honor verified
              requests free of charge.
            </p>
            <p>
              EU/UK residents: you have the rights described in GDPR and UK
              GDPR. Our lawful basis for processing is consent (for SMS) and
              legitimate interest (for contact inquiries).
            </p>
          </Section>

          <Section title="SMS specifics">
            <ul>
              <li>We only send SMS to contacts who have explicitly opted in via our <Link href="/sms" className={linkCls}>SMS opt-in page</Link> or via our contact form.</li>
              <li>Up to 10 messages per month. Message and data rates may apply.</li>
              <li>Reply <span className="font-mono">STOP</span> to unsubscribe, <span className="font-mono">HELP</span> for help.</li>
              <li>
                We do not share SMS opt-in data with any third party for
                marketing purposes. The phone numbers and consent records stay
                between you, Black Hart Consulting, and our SMS carrier (Quo).
              </li>
            </ul>
          </Section>

          <Section title="Security">
            <p>
              We use HTTPS site-wide, encrypted backups, and scope admin
              access to a small team. No system is perfectly secure; if we
              become aware of a breach that affects your information, we will
              notify you without undue delay.
            </p>
          </Section>

          <Section title="Changes to this policy">
            <p>
              If we make material changes, we&rsquo;ll update the &ldquo;Last
              updated&rdquo; date at the top and, where appropriate, notify
              you by email or SMS (if you&rsquo;re opted in).
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about this policy? Email{' '}
              {emailHrefVal ? <a href={emailHrefVal} className={linkCls}>{email}</a> : email}
              {' '}or call{' '}
              {phoneHrefVal ? <a href={phoneHrefVal} className={cn(linkCls, 'font-mono tracking-[0.02em]')}>{phone}</a> : phone}.
            </p>
          </Section>
        </div>
      </Container>

      <style>{`
        .prose > * + * { margin-top: 1.25em; }
        .prose h2 { font-family: var(--font-serif); font-weight: 600; font-size: 1.45em; line-height: 1.25; letter-spacing: -0.015em; margin: 2em 0 0.5em; }
        .prose p { margin: 0 0 0.75em; }
        .prose ul { margin: 0 0 1em; padding-left: 1.3em; }
        .prose li { margin: 0.3em 0; }
        .prose li::marker { color: var(--color-fg-muted); }
        .prose strong { color: var(--color-fg); font-weight: 600; }
      `}</style>
    </div>
  )
}

const linkCls = 'underline decoration-dotted underline-offset-2 hover:text-[var(--color-brass)]'

function cn(...parts: (string | false | undefined)[]) {
  return parts.filter(Boolean).join(' ')
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2>{title}</h2>
      {children}
    </section>
  )
}
