/* Manually-maintained Payload admin importMap.
   Normally generated by `payload generate:importmap`, but our ESM/tsx setup
   doesn't let the CLI resolve extensionless .ts imports from payload.config.
   Map every component the admin schema references by its "<package>#<export>" key. */

import { CollectionCards as CollectionCards_0 } from '@payloadcms/next/rsc'
import { RscEntryLexicalCell as RscEntryLexicalCell_0 } from '@payloadcms/richtext-lexical/rsc'
import { RscEntryLexicalField as RscEntryLexicalField_0 } from '@payloadcms/richtext-lexical/rsc'
import { LexicalDiffComponent as LexicalDiffComponent_0 } from '@payloadcms/richtext-lexical/rsc'
import { InlineToolbarFeatureClient as InlineToolbarFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { FixedToolbarFeatureClient as FixedToolbarFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { HeadingFeatureClient as HeadingFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { ParagraphFeatureClient as ParagraphFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { UnderlineFeatureClient as UnderlineFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { BoldFeatureClient as BoldFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { ItalicFeatureClient as ItalicFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { LinkFeatureClient as LinkFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { RelationshipFeatureClient as RelationshipFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { ChecklistFeatureClient as ChecklistFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { OrderedListFeatureClient as OrderedListFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { UnorderedListFeatureClient as UnorderedListFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { IndentFeatureClient as IndentFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { AlignFeatureClient as AlignFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { BlockquoteFeatureClient as BlockquoteFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { UploadFeatureClient as UploadFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { InlineCodeFeatureClient as InlineCodeFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { SubscriptFeatureClient as SubscriptFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { SuperscriptFeatureClient as SuperscriptFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { StrikethroughFeatureClient as StrikethroughFeatureClient_0 } from '@payloadcms/richtext-lexical/client'
import { S3ClientUploadHandler as S3ClientUploadHandler_0 } from '@payloadcms/storage-s3/client'
import AdminIcon_0 from '@/components/admin/Icon'
import AdminLogo_0 from '@/components/admin/Logo'
import RatingField_0 from '@/components/admin/RatingField'
import CentsAsDollarsField_0 from '@/components/admin/CentsAsDollarsField'
import CentsAsDollarsCell_0 from '@/components/admin/CentsAsDollarsCell'
import SendCarePlanSignupField_0 from '@/components/admin/SendCarePlanSignupField'
import ClientRelatedRecordsField_0 from '@/components/admin/ClientRelatedRecordsField'
import DelinquentBadgeCell_0 from '@/components/admin/DelinquentBadgeCell'
import ChangeTierField_0 from '@/components/admin/ChangeTierField'
import QuickCreateInvoiceField_0 from '@/components/admin/QuickCreateInvoiceField'
import RevenueByLpDashboard_0 from '@/components/admin/RevenueByLpDashboard'
import KpiStrip_0 from '@/components/admin/KpiStrip'
import InitNavPrefs_0 from '@/components/admin/InitNavPrefs'
import DashboardQuickActions_0 from '@/components/admin/DashboardQuickActions'
import RecentActivityPanel_0 from '@/components/admin/RecentActivityPanel'
import ActionQueue_0 from '@/components/admin/ActionQueue'
import DocActivityField_0 from '@/components/admin/DocActivityField'

export const importMap = {
  '@payloadcms/next/rsc#CollectionCards': CollectionCards_0,
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell': RscEntryLexicalCell_0,
  '@payloadcms/richtext-lexical/rsc#RscEntryLexicalField': RscEntryLexicalField_0,
  '@payloadcms/richtext-lexical/rsc#LexicalDiffComponent': LexicalDiffComponent_0,
  '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient_0,
  '@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient': FixedToolbarFeatureClient_0,
  '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient_0,
  '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient_0,
  '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient_0,
  '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient_0,
  '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient_0,
  '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient_0,
  '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient_0,
  '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient_0,
  '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient_0,
  '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient_0,
  '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient_0,
  '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient_0,
  '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient_0,
  '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient_0,
  '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient_0,
  '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient_0,
  '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient_0,
  '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient_0,
  '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient_0,
  '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler_0,
  '/components/admin/Icon#default': AdminIcon_0,
  '/components/admin/Logo#default': AdminLogo_0,
  '/components/admin/RatingField#default': RatingField_0,
  '/components/admin/CentsAsDollarsField#default': CentsAsDollarsField_0,
  '/components/admin/CentsAsDollarsCell#default': CentsAsDollarsCell_0,
  '/components/admin/SendCarePlanSignupField#default': SendCarePlanSignupField_0,
  '/components/admin/ClientRelatedRecordsField#default': ClientRelatedRecordsField_0,
  '/components/admin/DelinquentBadgeCell#default': DelinquentBadgeCell_0,
  '/components/admin/ChangeTierField#default': ChangeTierField_0,
  '/components/admin/QuickCreateInvoiceField#default': QuickCreateInvoiceField_0,
  '/components/admin/RevenueByLpDashboard#default': RevenueByLpDashboard_0,
  '/components/admin/KpiStrip#default': KpiStrip_0,
  '/components/admin/InitNavPrefs#default': InitNavPrefs_0,
  '/components/admin/DashboardQuickActions#default': DashboardQuickActions_0,
  '/components/admin/RecentActivityPanel#default': RecentActivityPanel_0,
  '/components/admin/ActionQueue#default': ActionQueue_0,
  '/components/admin/DocActivityField#default': DocActivityField_0,
}
